---

- hosts: all
  become: true
  tasks:
  - name: update repository index
    apt:
      update_cache: yes

  - name: install apache2 package
    apt:
      name: apache2
      state: latest

  - name: Start apache2 server
    service:
      name: apache2
      state: restarted

  - name: Add php support for apache2
    apt:
      name: libapache2-mod-php
      state: latest
 