---

- hosts: all
  become: true
  tasks:

  - name: Stop apache2 server
    service:
      name: apache2
      state: stopped

  - name: update repository index
    apt:
      update_cache: yes

  - name: Remove apache2 package (state absent)
    apt:
      name: apache2
      state: absent

  - name: Remove php support for apache2 (with state absent)
    apt:
      name: libapache2-mod-php
      state: absent
 