---

# First some tasks for all hosts 
- hosts: all
  become: true
  pre_tasks:

  - name: install updates (Ubuntu)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"


# Video13 managing users
- hosts: all
  become: true
  tasks:
  - name: create simone user
    tags: always
    user:
      name: simone
      group: root

  - name: add ssh key for simone (use keycontainer)
    tags: always
    authorized_key:
      user: simone
      key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDxiENRv6uRTq9aD7Qg+mNPm2KqZ9DDc3YuPIHwRRfqwXwRi5jn3rmkObWGZgR7oO+JgUhxMNlJDTkoT49TaTYcLQofTjHBB70ryEoXHyi+FFCSlaSA5mV9QNj5/UUT8Z/MKRfh/YJeyD9BZ+0iUmw5lAM5TO/knKh2I4i2++Sd8RPQQT6NmRJRvTWkA8RtprCbYnyo5EFuKaGh0AMQTI65SbabFLZM8Rh1rrKoGzrim0hqWxw4MfiDDHnEwuMxeXKjTyidvzaU4IQgOJw6jv3HNZvs36MOxK+u9mEM8z87NYJsS9U/ohO+m5hJLAi+3Aq16ot2tCp1qXxtUyL6SvMFd53Zp48T7sktOQecCv3E4YgFMcuw4UaGmfIet34rnJvgwVQ+UdNGn5NmYJ0P2qs3ITIvyOe/JJ/JinAu2n7oNhCIJoggH0FW/ovZhfEhE8+mzqgWFkty5E6zLALBnw9R1JHAGKzevhuR2jkptObk8P4MuOY8Q65c4hnYEtc7td8= grillo@p2017"    

  - name: add sudoers file for simone
    tags: always
    copy:
      src: sudoer_simone
      dest: /etc/sudoers.d/simone
      owner: root
      group: root
      mode: 0440
      

# Now the web_servers
- hosts: web_servers
  become: true
  tasks:

  - name: install apache2 and php for ubuntu servers
    tags: apache,apache2,ubuntu
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: copy default html file for site
    tags: apache,apache2,ubuntu
    copy: 
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644



  - name: Start apache2 server
    service:
      name: apache2
      state: restarted


# Now the db_servers
- hosts: db_servers
  become: true
  tasks:

  - name: install mariadb package (Ubuntu)
    tags: db,mariadb,ubuntu
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: Start mariadb server
    service:
      name: mysql
      state: started


# And now the file_servers
- hosts: file_servers
  become: true
  tasks:

  - name: install samba 
    tags: samba
    package:        # Can use package instead of apt. package can work ubuntu and centos
      name: samba
      state: latest
    when: ansible_distribution == "Ubuntu"


# This is an example to copy from internet and unzip
- hosts: workstations
  become: true
  tasks:

  - name: install unzip 
    package:        # Can use package instead of apt. package can work ubuntu and centos
      name: unzip

  - name: install terraform from internet 
    unarchive:       
      src: https://releases.hashicorp.com/terraform/0.12.28/terraform_0.12.28_linux_amd64.zip
      dest: /usr/local/bin
      remote_src: yes
      mode: 0755
      owner: root
      group: root


