---

# First some tasks for all hosts 
- hosts: all
  become: true
  pre_tasks:

  - name: install updates (Ubuntu)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"


# Video13 managing users
- hosts: all
  become: true
  roles:
    - base

# Now the web_servers
- hosts: web_servers
  become: true
  roles:
    - web_servers 

# Now the db_servers
- hosts: db_servers
  become: true
  roles:
    - db_servers


# And now the file_servers
- hosts: file_servers
  become: true
  roles:
    - file_servers

# And now the workstations
- hosts: workstations
  become: true
  roles:
    - workstations
